name: Run All Notebooks

on: workflow_dispatch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  notebook_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Docker in Docker Container
      run: docker run rboarman/example_env:latest
